[default.general]
chip = "STM32F407VETx"  # или STM32F407ZGTx в зависимости от вашей платы

[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true

[default.reset]
halt_afterwards = true
enabled = true

[default.rtt]
enabled = true
